@baseUrl = http://localhost:7071/api
@winner = {{GetElosToVote.response.body.$[0].PicId1}}
@loser = {{GetElosToVote.response.body.$[0].PicId2}}

###
DELETE {{baseUrl}}/DeletePicture

###
POST {{baseUrl}}/EditName

###
POST {{baseUrl}}/GenerateNewElo

###
GET {{baseUrl}}/GetAllElos

###
# @name GetElosToVote
GET {{baseUrl}}/GetElosToVote

###
GET {{baseUrl}}/GetRandomCarName

###
PUT {{baseUrl}}/NewElo

###
POST {{baseUrl}}/ResetEloVoting

###
POST {{baseUrl}}/VoteElo/?winner={{winner}}&loser={{loser}}
